baseURL = "https://piotr.is/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Sound & Complete"
copyright = "© 2009—2026 Piotr Kaźmierczak"

enableEmoji = true
enableRobotsTXT = true

summaryLength = 0

[outputs]
  home = ["HTML", "RSS"]

[permalinks]
  posts = "/:year/:slug/"
  page = "/:contentbasename/"

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
