# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://piotr.is/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Sound & Complete"
copyright = "© 2009—2026 Piotr Kaźmierczak"

enableEmoji = true
enableRobotsTXT = true

summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
  posts = "/:year/:slug/"
  page = "/:contentbasename/"

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
