# [[main]]
#   name = "'Gram"
#   url = "https://instagram.com/pete_casmerry"
#   weight = 10
# 
# [[main]]
#   name = "Github"
#   url = "https://github.com/pkazmierczak"
#   weight = 20

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "All articles"
  url = "/posts"
  weight = 1

[[footer]]
  name = "'Gram"
  url = "https://instagram.com/pete_casmerry"
  weight = 3

[[footer]]
  name = "Github"
  url = "https://github.com/pkazmierczak"
  weight = 4

[[footer]]
  name = "RSS"
  url = "/index.xml"
  weight = 5
