[[main]]
  name = "About"
  url = "/about"
  weight = 10

[[main]]
  name = "Research"
  url = "/research"
  weight = 15

[[main]]
  name = "Articles"
  url = "/post"
  weight = 20

# [[main]]
#   name = "Photographs"
#   url = "/photo"
#   weight = 30


# [[main]]
#   name = "Topics"
#   url = "/tags"
#   weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "Site info"
  url = "/website"
  weight = 10

[[footer]]
  name = "Contact"
  url = "/contact"
  weight = 25
