language: go
install:
  - sudo pip install awscli Pygments 
  - curl -L https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.tar.gz | tar xvz
script:
  - ./hugo
  - aws s3 sync public/ s3://piotr.is --region eu-central-1 --delete
notifications:
  email:
    on_failure: always