baseurl = "https://piotr.is/"
languageCode = "en-us"
title = "Piotr Kaźmierczak"
enableEmoji = true
footnotereturnlinkcontents = "↩"
pygmentsuseclasses = true
MetaDataFormat = "yaml"
canonifyURLs = true

[taxonomies]
  location = "locations"
  tag = "tags"

[outputs]
    home = ["HTML", "RSS"]
    page = ["HTML"]

[outputFormats.RSS]
    path = "/feed/"

[permalinks]
    post = "/:year/:slug/"
    page = "/:title/"

[author]
    name = "Piotr Kaźmierczak"

[params]
    description = "A personal blog."
    author = "Piotr Kaźmierczak"

[markup.goldmark.renderer]
    unsafe= true

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

