baseurl = "https://piotr.is/"
languageCode = "en-us"
title = "Sound & Complete"
enableEmoji = true
footnotereturnlinkcontents = "↩"
pygmentsuseclasses = true
MetaDataFormat = "yaml"
googleAnalytics = "UA-26225127-4"

[outputFormats.RSS]
    path = "/feed/"

[permalinks]
    post = "/:year/:slug/"
    page = "/:title/"

[author]
    name = "Piotr Kaźmierczak"

[params]
    description = "A personal blog."
    author = "Piotr Kaźmierczak"

[markup.goldmark.renderer]
    unsafe= true

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

