[build]
  command = "git submodule init && git submodule update && hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.16"
  TZ = "CEST"  # Set to preferred timezone

[context.production.environment]
  HUGO_VERSION = "0.96.0"
  HUGO_ENV = "production"
