version: 2
jobs:
  build:
    docker:
      - image: alpine:3
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:

      # install git
      - run: apk update && apk add git curl

      # checkout the repository
      - checkout

      # install git submodules for managing third-party dependencies
      - run: git submodule sync && git submodule update --init

      # install hugo
      - run: curl -L https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.tar.gz | tar xvz

      - run:
          name: install AWS CLI (first install pip, the Python package manager)
          command: |
            apk add --update python python-dev py-pip build-base
            pip install awscli

      # build with Hugo
      - run: HUGO_ENV=production ./hugo -v -d $HUGO_BUILD_DIR

      # `deploy` step: identical to a `run` step, but uses only one container:
      # https://circleci.com/docs/2.0/configuration-reference/#deploy
      - deploy:
          name: deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync $HUGO_BUILD_DIR \
              s3://piotr.is --region eu-central-1 --delete --metadata-directive \
              REPLACE --cache-control max-age=2592000
              aws cloudfront create-invalidation --distribution-id E2COJD5GHJ1RXH --paths "/*"
              aws cloudfront create-invalidation --distribution-id E1FETIAV1VSAJ0 --paths "/*"
            else
              echo "Not master branch, dry run only"
            fi
