---
label: default
hide_body: false
fields:
- type: text
  name: slug
  label: slug
- type: datetime
  name: date
  label: date
- type: text
  name: location
  label: location
- type: list
  name: tags
  label: tags
pages:
- content/post/2019-11-01-cali.md
